apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    email: {{ .Values.acmeEmail | quote }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    solvers:
    - dns01:
        azureDNS:
          clientID: {{ default "" .Values.azure.clientID | quote }}
          clientSecretSecretRef:
          # The following is the secret we created in Kubernetes. Issuer will use this to present challenge to Azure DNS.
            name: azuredns-config
            key: client-secret
          subscriptionID: {{ default "" .Values.azure.subscriptionID | quote }}
          tenantID: {{ default "" .Values.azure.tenantID | quote }}
          resourceGroupName: {{ default "" .Values.azure.resourceGroupName | quote }}
          hostedZoneName: {{ default "" .Values.azure.hostedZoneName | quote }}
          # Azure Cloud Environment, default to AzurePublicCloud
          environment: {{ default "" .Values.azure.environment | quote }}