apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.issuerName }}
spec:
  acme:
    email: {{ .Values.acmeEmail | quote }}
    server: {{ .Values.acmeServer | quote }}
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    solvers:
    - dns01:
        azureDNS:
          clientID: {{ required "A valid azure.clientID entry required!" .Values.azure.clientID | quote }}
          clientSecretSecretRef:
          # The following is the secret we created in Kubernetes. Issuer will use this to present challenge to Azure DNS.
            name: azuredns-config
            key: client-secret
          subscriptionID: {{ required "A valid azure.subscriptionID entry required!" .Values.azure.subscriptionID | quote }}
          tenantID: {{ required "A valid azure.tenantID entry required!" .Values.azure.tenantID | quote }}
          resourceGroupName: {{ required "A valid azure.resourceGroupName entry required!" .Values.azure.resourceGroupName | quote }}
          hostedZoneName: {{ required "A valid azure.hostedZoneName entry required!" .Values.azure.hostedZoneName | quote }}
          # Azure Cloud Environment, default to AzurePublicCloud
          environment: {{ required "A valid azure.environment entry required!" .Values.azure.environment | quote }}